---
title: "qmm assignment 2"
Name: "Agasthya katkam"
output:
  html_document:
    df_print: paged
  pdf_document: default
date: "2023-09-25"
---
#Question

The Weigelt Corporation has three branch plants with excess production capacity. Fortunately,
the corporation has a new product ready to begin production, and all three plants have this
capability, so some of the excess capacity can be used in this way. This product can be made in
three sizes--large, medium, and small--that yield a net unit profit of $420, $360, and $300,
respectively. Plants 1, 2, and 3 have the excess capacity to produce 750, 900, and 450 units per
day of this product, respectively, regardless of the size or combination of sizes involved.
The amount of available in-process storage space also imposes a limitation on the production
rates of the new product. Plants 1, 2, and 3 have 13,000, 12,000, and 5,000 square feet,
respectively, of in-process storage space available for a day's production of this product. Each
unit of the large, medium, and small sizes produced per day requires 20, 15, and 12 square feet,
respectively.
Sales forecasts indicate that if available, 900, 1,200, and 750 units of the large, medium, and
small sizes, respectively, would be sold per day.
At each plant, some employees will need to be laid off unless most of the plant’s excess
production capacity can be used to produce the new product. To avoid layoffs if possible,
management has decided that the plants should use the same percentage of their excess capacity
to produce the new product.
Management wishes to know how much of each of the sizes should be produced by each of the
plants to maximize profit.


Answer:

Formulation of LP problem

The objective function is Max Z = 420(L1 + L2 + L3) + 360(M1 + M2 + M3) + 300(S1 + S2 + S3)

Rearraning the objective function Max Z = 420L1+360M1+300S1+420L2+360M2+300S2+420L3+360M3+300S3 

subject to
                    L1 + M1 + S1 ≤ 750
                    
                    L2 + M2 + S2 ≤ 900
                    
                    L3 + M3 + S3 ≤ 450
                    
                    20L1 + 15M1 + 12S1 ≤ 13000
                    
                    20L2 + 15M2 + 12S2 ≤ 12000
                    
                    20L3 + 15M3 + 12S3 ≤ 5000
                    
                    L1 + L2 + L3 ≤ 900
                    
                    M1 + M2 + M3 ≤ 1200
                    
                    S1 + S2 + S3 ≤ 750

Non negativity constraints 
        
        L1, L2, L3, M1, M2, M3, S1, S2, S3 ≥ 0

The above LP problem constaraints can be written as


L1 + M1 + S1 + 0L2 + 0M2 + 0S2 + 0L3 + 0M3 + 0S3 ≤ 750

0L1 + 0M1 + 0S1 + L2 + M2 + S2 + 0L3 + 0M3 + 0S3 ≤ 900

0L1 + 0M1 + 0S1 + 0L2 + 0M2 + 0S2 + L3 + M3 + S3 ≤ 450

20L1 + 15M1 + 12S1 + 0L2 + 0M2 + 0S2 + 0L3 + 0M3 + 0S3 ≤ 13000

0L1 + 0M1 + 0S1 + 20L2 + 15M2 + 12S2 + 0L3 + 0M3 + 0S3 ≤ 12000

0L1 + 0M1 + 0S1 + 0L2 + 0M2 + 0S2 + 20L3 + 15M3 + 12S3 ≤ 5000

L1 + 0M1 + 0S1 + L2 + 0M2 + 0S2 + L3 + 0M3 + 0S3 ≤ 900

0L1 + M1 + 0S1 + 0L2 + M2 + 0S2 + 0L3 + M3 + 0S3 ≤ 1200

0L1 + 0M1 + S1 + 0L2 + 0M2 + S2 + 0L3 + 0M3 + S3 ≤ 750



```{r}
##install the required packages
#install.packages("lpsolve")
library(lpSolve)
 
#the objective function is to maximize Z
#Z = 420L1+360M1+300S1+420L2+360M2+300S2+420L3+360M3+300S3

f.obj<-c(420,360,300,420,360,300,420,360,300)
#matrix form of constraints
f.con <-matrix(c(1,1,1,0,0,0,0,0,0,
                 0,0,0,1,1,1,0,0,0,
                 0,0,0,0,0,0,1,1,1,
                 20,15,12,0,0,0,0,0,0,
                 0,0,0,20,15,12,0,0,0,
                 0,0,0,0,0,0,20,15,12,
                 1,0,0,1,0,0,1,0,0,
                 0,1,0,0,1,0,0,1,0,
                 0,0,1,0,0,1,0,0,1), nrow = 9, byrow = TRUE)

# set the direction of the inequalities using subject to equation for this.
f.dir <-c("<=",
          "<=",
          "<=",
          "<=",
          "<=",
          "<=",
          "<=",
          "<=",
          "<=")

#set right hand side of the coefficients
f.rhs <-c(750,900,450,13000,12000,5000,900,1200,750)

lp("max", f.obj, f.con, f.dir, f.rhs)
#values of variables
lp("max", f.obj, f.con, f.dir, f.rhs)$solution


```